name       : btop
version    : 1.2.13
release    : 1
source     :
    - https://github.com/aristocratos/btop/archive/refs/tags/v1.2.13.tar.gz : 668dc4782432564c35ad0d32748f972248cc5c5448c9009faeb3445282920e02
license    : Apache-2.0
component  : system.utils
summary    : btop is a monitor of system resources.
description: |
    Resource monitor that shows usage and stats for processor, memory, disks, network and processes. C++ version and continuation of bashtop and bpytop.
build      : |
    %make 
install    : |
    %make_install PREFIX=/usr
